// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzfkkdczshauslcbewqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6ZmtrZGN6c2hhdXNsY2Jld3FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTA0OTQsImV4cCI6MjA2MzI4NjQ5NH0.s5QlBuiVaJNB5upMgmAzBAex9ALNQuRUaOKx5nQaQXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);