// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rigluylhplrrlfkssrur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpZ2x1eWxocGxycmxma3NzcnVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwOTAwMTUsImV4cCI6MjA3MTY2NjAxNX0.GNltlbsZLrBHNe52b1Vk5Cm6rZPOk11FtuaoDm3waLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});